Goal: gauge ingagement between tradition and digital art on twitter

In [1]:
import requests
import pandas as pd
import json
import urllib
import matplotlib

Linking to the Twitter API

In [2]:
bearer_token = pd.read_csv("twitterApp.txt", header = 0)

In [3]:
token = bearer_token['Bearer Token'].iloc[0]

In [4]:
header = {'Authorization' : 'Bearer {}'.format(token)}

In [5]:
endpoint_url = 'https://api.twitter.com/2/tweets/search/recent'

Query to display posts using the hashtags of digital and traditional art

In [6]:
query = urllib.parse.quote('(#digitalart OR #traditionalart) -is:retweet')

In [7]:
tweet_fields = 'author_id,id,text,public_metrics,created_at,entities'

In [8]:
url = endpoint_url + '?query={}&tweet.fields={}&user.fields={}&max_results=100'.format(query,tweet_fields,"username")

In [9]:
response_1 = requests.request("GET", url, headers=header)

In [10]:
response_1_dict = json.loads(response_1.text)

In [15]:
page1 = pd.DataFrame(response_1_dict['data'])

In [23]:
page1

,public_metrics,entities,text,created_at,author_id,id
0,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'mentions': [{'start': 0, 'end': 9, 'username...",@SNFonNBC @NBCSports BIG NEWS Top Crypto Gaine...,2021-11-30T21:51:57.000Z,780399227675475968,1465800793962037249
1,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'mentions': [{'start': 0, 'end': 8, 'username...",@opensea \n https://t.co/dDV3ecIzTb\n.\n#nftar...,2021-11-30T21:51:46.000Z,1461067796046036994,1465800748223152130
2,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'mentions': [{'start': 0, 'end': 9, 'username...",@Quackity @Ranboosaysstuff BIG NEWS Top Crypto...,2021-11-30T21:51:44.000Z,780399227675475968,1465800739566104582
3,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'mentions': [{'start': 0, 'end': 16, 'usernam...",@Ranboosaysstuff BIG NEWS Top Crypto Gainers =...,2021-11-30T21:51:28.000Z,780399227675475968,1465800673631604741
4,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'hashtags': [{'start': 74, 'end': 85, 'tag': ...",blue haired girl.üòç adopt ne soon with 0.005 e...,2021-11-30T21:51:26.000Z,1458706080066949121,1465800665381457927
...,...,...,...,...,...,...
95,"{'retweet_count': 2, 'reply_count': 0, 'like_c...","{'annotations': [{'start': 16, 'end': 21, 'pro...","Before you meet Hokori in chapter 1, I want to...",2021-11-30T21:41:06.000Z,1401286275152461834,1465798064065634307
96,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'annotations': [{'start': 27, 'end': 33, 'pro...",Hey all! Here's my take on Caitlyn and Vi from...,2021-11-30T21:40:52.000Z,1353067640843952128,1465798005924065280
97,"{'retweet_count': 0, 'reply_count': 2, 'like_c...","{'hashtags': [{'start': 71, 'end': 87, 'tag': ...",Commission Open Now\nDM me if interested&lt;3\...,2021-11-30T21:40:44.000Z,1444856854614458370,1465797971748950020
98,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'hashtags': [{'start': 12, 'end': 16, 'tag': ...",Zombie Baby\n#art #illustration #digitalart #n...,2021-11-30T21:40:34.000Z,1454344433529393155,1465797931903164424
99,"{'retweet_count': 0, 'reply_count': 0, 'like_c...","{'hashtags': [{'start': 0, 'end': 5, 'tag': 'n...",#nfts #nft #nftart #nftartist #nftcollector #c...,2021-11-30T21:40:30.000Z,1357472970705416193,1465797911892180992

In [21]:
metrics = pd.DataFrame(list(page1['public_metrics']))

In [22]:
metrics

    retweet_count  reply_count  like_count  quote_count
0               0            0           0            1
1               0            0           1            0
2               0            0           0            0
3               0            0           0            0
4               0            0           1            0
..            ...          ...         ...          ...
95              2            0           2            0
96              0            0           0            0
97              0            2           0            0
98              0            0           3            0
99              0            0           3            0

[100 rows x 4 columns]